FROM alpine:3.21

ARG UID=1001
ARG GID=1001
ARG USER_NAME=admin
ARG GROUP_NAME=ateng
ARG WORK_DIR=/opt/app

WORKDIR ${WORK_DIR}

COPY --from=eclipse-temurin:21-jdk-alpine --chown=${UID}:${GID} /opt/java/openjdk /opt/jdk
COPY --chown=${UID}:${GID} docker-entrypoint.sh .
COPY --chown=${UID}:${GID} springboot3-demo-v1.0.jar .

RUN set -eux && \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update && \
    apk upgrade && \
    apk add --no-cache \
        tzdata \
        curl \
        ca-certificates \
        font-noto-cjk \
        su-exec \
        shadow \
        bash \
        icu-data-full && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    groupadd -g ${GID} ${GROUP_NAME} && \
    useradd -u ${UID} -g ${GROUP_NAME} -m ${USER_NAME} && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

ENV JAVA_HOME=/opt/jdk
ENV PATH=$PATH:$JAVA_HOME/bin
ENV TZ=Asia/Shanghai
ENV LANG=zh_CN.UTF-8
ENV LANGUAGE=zh_CN:zh
ENV LC_ALL=zh_CN.UTF-8

USER ${UID}:${GID}

ENTRYPOINT ["./docker-entrypoint.sh"]
