# 环境
FROM debian:12.8

# 作者信息
LABEL maintainer="KongYu <2385569970@qq.com>"
# 设置容器的描述信息
LABEL description="操作系统版本是：debian:12.8，Java版本是：Eclipse Temurin发版的OpenJDK 17"
# 添加其他标签
LABEL release-date="2024-12-07"

# 拷贝数据
ADD OpenJDK11U-*.tar.gz /opt/

# 定位到指定目录
WORKDIR /opt

# 设置 JDK 相关的环境变量
ENV JAVA_HOME=/opt/jdk11
ENV PATH=$PATH:$JAVA_HOME/bin

# 设置时区
ENV TZ=Asia/Shanghai

# 安装软件
RUN sed -i "s#http.*\(com\|org\|cn\)#http://mirrors.aliyun.com#g" /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt-get upgrade -y && \
    apt-get install -y locales curl unzip zip vim net-tools iproute2 iputils-ping less wget jq dnsutils traceroute tcpdump nmap fontconfig fonts-dejavu-core fonts-liberation && \
    apt-get clean && \
    echo "zh_CN.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen zh_CN.UTF-8 && \
    update-locale LANG=zh_CN.UTF-8 && \
    groupadd -g 1001 ateng && \
    useradd -u 1001 -g ateng -m admin && \
    chown 1001:1001 -R /opt && \
    mv /opt/jdk-11* /opt/jdk11 && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# 设置编码
ENV LANG=zh_CN.UTF-8
ENV LANGUAGE=zh_CN:zh
ENV LC_ALL=zh_CN.UTF-8

# 设置用户
USER 1001:1001

# 设置容器的启动命令
CMD ["java", "-version"]
