global:
  security:
    allowInsecureImages: true
  defaultStorageClass: ""
  redis:
    password: "Admin@123"
fullnameOverride: "redis"
image:
  debug: false
  registry: registry.lingo.local
  repository: bitnami/redis
  tag: "8.0.1"
  pullPolicy: IfNotPresent
architecture: standalone
auth:
  enabled: true
commonConfiguration: |-
  databases 20
  appendonly yes
  appendfsync always
  save ""
  maxclients 1024
  maxmemory 8GB
  auto-aof-rewrite-percentage 100
  auto-aof-rewrite-min-size 64mb
  maxmemory-policy volatile-lru
  io-threads 8
  io-threads-do-reads yes
  loadmodule /opt/bitnami/redis/lib/redis/modules/redisbloom.so
  loadmodule /opt/bitnami/redis/lib/redis/modules/redisearch.so
  loadmodule /opt/bitnami/redis/lib/redis/modules/rejson.so
  loadmodule /opt/bitnami/redis/lib/redis/modules/redistimeseries.so

master:
  disableCommands:
    - FLUSHDB
    - FLUSHALL
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  containerPorts:
    redis: 6379
  resources:
    limits: {}
    requests: {}
  affinity: {}
  nodeSelector: {}
  persistence:
    size: 50Gi
  service:
    type: NodePort
    ports:
      redis: 6379
    nodePorts:
      redis: ""

metrics:
  enabled: true
  image:
    registry: registry.lingo.local
    repository: bitnami/redis-exporter
    tag: "1.71.0"
    pullPolicy: IfNotPresent
  redisTargetHost: "localhost"
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  service:
    type: ClusterIP
    port: 9121
