global:
  storageClass: ""
fullnameOverride: "mariadb"
image:
  registry: docker.io
  repository: bitnami/mariadb
  tag: "11.3.2"
  pullPolicy: IfNotPresent
  debug: false
## @param architecture MariaDB architecture (`standalone` or `replication`)
architecture: standalone
auth:
  rootPassword: ""
  database: kongyu
  username: "kongyu"
  password: "kongyu"
primary:
  name: primary
  configuration: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    datadir=/bitnami/mariadb/data
    plugin_dir=/opt/bitnami/mariadb/plugin
    port={{ .Values.primary.containerPorts.mysql }}
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=100M
    bind-address=*
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=utf8mb4
    collation-server=utf8mb4_general_ci
    init_connect='SET NAMES utf8mb4'
    slow_query_log=0
    slow_query_log_file=/bitnami/mariadb/data/slow_query.log
    long_query_time=10.0
    default_time_zone="+8:00"
    lower_case_table_names=0
    max_connections=1024
    max_connect_errors=1024
    server-id=1
    log-bin=mariadb-bin
    max_binlog_size=1024M
    binlog_expire_logs_seconds=86400

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

  resourcesPreset: "none"
  resources: {}
  affinity: {}
  nodeSelector: {}
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: "1Gi"
  #   requests:
  #     cpu: "500m"
  #     memory: "512Mi"
  # ## Allowed values: `soft` or `hard`
  # #podAffinityPreset: "soft"  ## 调度到同一节点
  podAntiAffinityPreset: "soft"  ## 调度到不同节点
  nodeAffinityPreset:  ## 调度到包含指定标签的节点，例如创建节点标签：kubectl label node server02.lingo.local kubernetes.service/mariadb="true"
    type: "soft"
    key: "kubernetes.service/mariadb"
    values:
      - "true"
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  persistence:
    size: 100Gi
  service:
    type: ClusterIP
    ports:
      mysql: 3306
      metrics: 9104
    nodePorts:
      mysql: ""
